server:
  port: 8086

security:
  oauth2:
    resourceserver:
      jwt:
        issuer: "https://smartbridgein.com"
        secret-key: "YourSuperStrongAndLongSecretKeyForHmacShaAlgorithmsAtLeast256Bits"
        audience: "MS"

services:
  inventory:
    url: http://localhost:8082
  payment-service:
    url: http://localhost:8084


# ===================================================================
# CUSTOM APPLICATION PROPERTIES
# ===================================================================
app:
  firebase:
    # Path to the service account key within the classpath.
    service-account-path: "google-services.json"
